baseURL = "https://mbt.ad/"
theme = "PaperMod"
title = "MBT"
defaultContentLanguage = "ar"

publishDir = "docs"

# --- Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ù„ØºØ© ---
[languages]
  [languages.ar]
    languageName = "Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©"
    languageCode = "ar"
    weight = 1
    title = "MBT"
    languageDirection = "rtl"

  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 2
    title = "MBT"
    languageDirection = "ltr"

# --- Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø¹Ø§Ù…Ø© ---
[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  hideMeta = true
  
  # Ø±Ø§Ø¨Ø· Ø§Ù„Ø­Ù‚ÙˆÙ‚ ÙŠÙˆØ¬Ù‡ Ù„Ù„ØµÙØ­Ø© Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ©
  copyright = "&copy; 2026 <a href=\"/\">MBT</a>"

  [params.assets]
    disableFingerprinting = true

# --- Ø§Ù„Ù‚ÙˆØ§Ø¦Ù… ---
[[menu.main]]
  identifier = "whatsapp"
  name = "Ø§Ù„ÙˆØ§ØªØ³Ø§Ø¨"
  url = "https://wa.me/9647872840590"
  weight = 10

[[menu.main]]
  identifier = "gallery"
  name = "Ø£Ø¹Ù…Ø§Ù„Ù†Ø§"
  url = "/gallery/"
  weight = 20
  pre = "ğŸ¬ "

[[menu.main]]
  identifier = "Services"
  name = "Ø®Ø¯Ù…Ø§ØªÙ†Ø§"
  url = "/Services/"
  weight = 30
  pre = "ğŸ’² "
  
# --- Ø¥Ø®ÙØ§Ø¡ Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ù…ÙŠØªØ§ Ø§Ù„Ø²Ø§Ø¦Ø¯Ø© ---
[[cascade]]
  [cascade.params]
    hidemeta = true

# --- Ø§Ù„Ø³Ù…Ø§Ø­ Ø¨ÙƒÙˆØ¯ HTML ÙÙŠ Ø§Ù„ØµÙØ­Ø§Øª ---
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true