baseURL = "https://mbt.ad/"
theme = "PaperMod"
title = "MBT"
defaultContentLanguage = "ar"

publishDir = "docs"

# --- إعدادات اللغة العربية (هنا التعديل المهم) ---
[languages]
  # اللغة العربية (الافتراضية)
  [languages.ar]
    languageName = "العربية"
    languageCode = "ar"
    weight = 1
    title = "MBT"
    languageDirection = "rtl"

  # اللغة الإنجليزية (الجديدة)
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 2
    title = "MBT"
    languageDirection = "ltr" # اتجاه يسار ليمين

# --- إعدادات رئيسية للموقع ---
[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  hideMeta = true
  
  [params.assets]
    disableFingerprinting = true

  images = ["/images/preview.png"]
  
  # --- تفعيل وضع الصيانة (Profile Mode) ---
  [params.profileMode]
    enabled = true
    title = "الموقع تحت الصيانة"
    subtitle = " " 
    imageUrl = "images/logo.png" 
    imageWidth = 200
    imageHeight = 200

# --- القوائم (Menus) ---
[[menu.main]]
  identifier = "whatsapp"
  name = "الواتساب"
  url = "https://wa.me/9647872840590"
  weight = 10

[[menu.main]]
  identifier = "gallery"
  name = "أعمالنا"
  url = "/gallery/"
  weight = 20

[[menu.main]]
  identifier = "Services"
  name = "خدماتنا"
  url = "/Services/"
  weight = 30
  
[[cascade]]
  [cascade.params]
    hidemeta = true
	
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true